<<<<<<< HEAD
language: node_js
notifications:
  email: false
node_js:
  - '6.0.0'
before_install:
  - travis_retry nvm install 6.0.0
  - travis_retry wget https://www.dropbox.com/s/heja4ryn45bd5wt/test.tar.gz?dl=0 -O test.tar.gz && tar xfvz test.tar.gz
env:
  global:
    - MERGE_TOKEN=7ec583e95b00bfab262215cb3bb41c5ec822951f
script:
  - npm test
=======
language: node_js
notifications:
  email: false
node_js:
  - '6.0.0'
before_install:
  - travis_retry nvm install 6.0.0
  - travis_retry wget https://www.dropbox.com/s/heja4ryn45bd5wt/test.tar.gz?dl=0 -O test.tar.gz && tar xfvz test.tar.gz
env:
  global:
    - MERGE_TOKEN=872c194d635f08bfda7c4805e70f082f152be65b
script:
  - npm test
>>>>>>> 58a1ca4f4342be2e7c3908264f03c09370b25d2e
